server {
    listen 8080;
    root /var/www/html;

    location /php {
        allow_methods GET POST;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html;
        fastcgi_param SCRIPT_FILENAME /var/www/other;
    }
}
