# Commentaire (ligne ignorée si elle commence par #)

server {
    listen              127.0.0.1:8080;
    listen              8081;                      # host par défaut 0.0.0.0
    server_name         localhost example.com;

    client_max_body_size 10M;                      # suffixes K / M / G

    error_page          404 /errors/404.html;
    error_page          500 502 503 /errors/50x.html;

    root                /home/lmilando;
    index               index.html index.htm;
	autoindex	on;

    location / {
        allow_methods   GET;                  # défaut: GET seul
        autoindex       off;
    }

    location /upload {
        allow_methods   POST DELETE;
        upload_store    /home/mzouhir/Documents/site/upload;
        client_max_body_size 50M;                  # override le server
    }

    location /old {
        return          301 /new;                  # redirection
    }

    location /php {
        allow_methods   GET POST;
        fastcgi_pass    127.0.0.1:9000;
        fastcgi_param   SCRIPT_FILENAME  /somewhere;
        fastcgi_param   QUERY_STRING     query_string;
    }

    location /cgi-bin {
        allow_methods   GET POST;
        cgi_pass        .py /usr/bin/python3;       # extension -> interpréteur
        cgi_pass        .php /usr/bin/php-cgi;
    }
}

server {
    listen              8083;
    server_name         other.com;
    root                /home/mzouhir/Documents/webserv;
}
